version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "1234:3000"
    depends_on:
      - backend

  db:
    image: coleifer/sqlite-web  # Official SQLite Web service
    environment:
      - SQLITE_DATABASE=./books.db  # Path to the SQLite DB
    ports:
      - "8080:8080"  # Expose SQLite Web interface
