version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "1234:3000"
    depends_on:
      - backend

  db:
    image: "nouchka/sqlite3"
    volumes:
      - ./backend/data:/var/db
    environment:
      - SQLITE_DB=books.db
